### ISSUE TITLE
Large performance gap of the code and paper

### ISSUE THREAD

**Issue by qyz55** [ling-pan/OMAR#3]
Hi, thanks for your impressive work! I'm running OMAR as a baseline of my algorithm. When I run the code(with original parameters including cql_alpha and omar_coe), I find the results of MPE  is consistent with the results in the paper, but the results of mamujoco is far from the data presented in the paper. I attach some results here:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/13428700/211200111-b3d64860-29de-426f-9a72-38593e87d42d.png">
And I tried many other methods including MACQL,  TD3+BC. Their best results are all lower than 1000, which results in a normalized score less than 30. Can you figure out what's wrong with my results? I think this may come from the environment difference. I use the newest mamujoco 1.1.0, and mujoco version 2.1.0. Are these configurations consistent with the dataset? The way for calculating normalized score may be another reason. Would you tell me the way of calculating the score? Is it the same as MPE? Thanks again!

**Comment by qyz55** [comment]
Fine, I find  the difference lies in the mujoco version. When I change from mujoco 2.1 to mujoco 2.0. The code works with return 3000.

**Comment by fyqqyf** [comment]
Hello,

I have noticed that there is no output or results generated when I run the code. Additionally, I couldn't find any code for saving models or logs in the main.py file. Can you confirm if you have successfully executed the code and provide any guidance to address this issue?

Thank you for your assistance!

@qyz55 @ling-pan
